# Generated by Django 5.1 on 2024-09-09 08:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('school_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=15)),
                ('address_area', models.CharField(max_length=100)),
                ('address_landmark', models.CharField(blank=True, max_length=100, null=True)),
                ('address_city', models.CharField(max_length=50)),
                ('address_state', models.CharField(max_length=50)),
                ('address_country', models.CharField(choices=[('us', 'United States'), ('uk', 'United Kingdom'), ('in', 'India')], max_length=50)),
                ('address_pincode', models.CharField(max_length=10)),
                ('organization_type', models.CharField(choices=[('school', 'School'), ('college', 'College')], max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SchoolRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_date', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('number', models.CharField(max_length=15)),
                ('fathers_name', models.CharField(max_length=100)),
                ('dob', models.DateField()),
                ('roll_no', models.CharField(max_length=20, unique=True)),
                ('student_class', models.CharField(max_length=20)),
                ('section', models.CharField(max_length=10)),
                ('fee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
